### PR TITLE
Add LICENSE.md so it gets packaged in the source dist

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I noticed there is an other license file in the folder PyMieScat, is that one no longer the license you want to release your code under? If so, can you please remove that file to make it clear.

**Comment by kmuehlbauer** [comment]
@bsumlin Your fine package is available now via `conda-forge` channel: https://github.com/conda-forge/pymiescatt-feedstock

For the packaging it would be great to get the licensing correct. If you need any help, please let me know.

**Comment by bsumlin** [comment]
Thanks for putting this on conda-forge! I’ve updated setup.py in the main repo to reflect the MIT license, and I’ve made a pull request on the conda package to update the license file.

-Ben

**Comment by kmuehlbauer** [comment]
@bsumlin Thanks for addressing the license issue within setup.py.

If you merge this PR, then your LICENCE.md will be added to the tarball when creating a source distribution.

Another thing is what @hmaarrfk mentioned: the license file in the PyMieScatt subfolder. This should be removed to clear the issue.

**Comment by kmuehlbauer** [comment]
@bsumlin Great! Thanks! The last thing in the license trouble is this file: https://github.com/bsumlin/PyMieScatt/blob/master/PyMieScatt/LICENSE

This file mentions GPL and is irritating. If this is not intended it is best to remove it completely.

**Comment by bsumlin** [comment]
@kmuehlbauer done!

**Comment by kmuehlbauer** [comment]
Perfect! Sorry for being kind of a nuisance here.

**Comment by hmaarrfk** [comment]
Thanks, this is just about being clear about your intentions as the author of this package!

The documentation about the license_file field is super obscure and I can't even find it now. I know that it works though and it is the only reliable way to get the license in the source dist that you publish. Thanks for doing this!

**Pull request merged**
